import { useSpaces } from '@graphprotocol/hypergraph-react';
import { createFileRoute, Link } from '@tanstack/react-router';

export const Route = createFileRoute('/')({
  component: Index,
});

function Index() {
  const { data: publicSpaces, isPending: publicSpacesPending } = useSpaces({ mode: 'public' });
  const { data: privateSpaces, isPending: privateSpacesPending } = useSpaces({ mode: 'private' });

  return (
    <div className="p-2">
      <h3 className="text-xl">Welcome Home!</h3>
      <p className="mt-2">This is your new application generated by Typesync.</p>
      <div className="mt-4">
        <h4 className="text-lg">Public Spaces</h4>
        <ul>
          {publicSpacesPending && <li>Loading public spaces...</li>}
          {!publicSpacesPending && publicSpaces?.length === 0 && <li>No public spaces found</li>}
          {publicSpaces?.map((space) => (
            <li key={space.id}>
              <Link to="/public-space/$space-id" params={{ 'space-id': space.id }}>
                {space.name}
              </Link>
            </li>
          ))}
        </ul>
      </div>
      <div className="mt-4">
        <h4 className="text-lg">Private Spaces</h4>
        <ul>
          {privateSpacesPending && <li>Loading private spaces...</li>}
          {!privateSpacesPending && privateSpaces?.length === 0 && <li>No private spaces found</li>}
          {privateSpaces?.map((space) => (
            <li key={space.id}>
              <Link to="/private-space/$space-id" params={{ 'space-id': space.id }}>
                {space.name}
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
